collections:
  publications:
    output: true
  blog:
    output: true
  notes:
    output: true
  tutorials:
    output: true

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "paper"
  
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "post"

  - scope:
      path: ""
    values:
      layout: "default"


url: "https://gczelusta.github.io"
github_username:  gczelusta
plugins:
  - jekyll-feed